### ISSUE TITLE
Add a container that uses glibc

### ISSUE THREAD

**Issue by lionah** [liferay/liferay-docker#11]
Though there are many packages available for the Alpine distro through their package manager, I've run into problems with the fact that they do not use glibc. I admit I don't remember what those problems where because I haven't used Alpine since.

**Comment by purzelification** [comment]
Alpine is bad in case you are using OpenJDK with a verison higher than 8 as it has a hard dependency on glibc. Since Alpine does no longer ship with glibc it will cause problems.

**Comment by ghenadiibatalski** [comment]
Could you please explain, what problems are you facing with alpine?

**Comment by h0otCh** [comment]
Alpine uses muslc. OpenJDK will not run properly since it needs glibc. Or ist my information outdated?

**Comment by ghenadiibatalski** [comment]
I don't know, we do first trial with Liferay on Alpine (similar to this image). Other services (eg. spring boot etc.) working well on alpine.

**Comment by h0otCh** [comment]
Ok so my mistake really. Misread a lot of information. The reason there was no alpine image with OpenJDK was because alpine does not contain glibc. Because of this, many programs **may** break, so the images needed to be tested more thoroughly. Right now there are actually images for Java 12 and 13 on top of alpine. However I have not yet seen a Java 11 image

**Comment by ghenadiibatalski** [comment]
Take a look at Azul openjdk 11 for alpine. Seems to be TCK certified (at least some builds)

**Comment by h0otCh** [comment]
Thank you, I will check them out!

**Comment by zsoltbalogh** [comment]
Hey everyone on this issue - it seems that the issue was discussed and we don't need to make changes. Please reopen the thread if I misunderstood the conversation. Thank you!
