### ISSUE TITLE
6.2.5-ga6 - Memory usage dynamic images not showing

### ISSUE THREAD

**Issue by jcorteslinkare** [liferay/liferay-docker#12]
docker image liferay/portal:6.2.5-ga6

Memory usage dynamic images are not showing, tested with Firefox and Chrome:

Admin > Control Panel > Server Administration > Resources

**Comment by zsoltbalogh** [comment]
@jcorteslinkare , I have just tested the latest images (working on #21) and they seem to work. Could you please verify? I'm closing this ticket as it seems we fixed the issue (screenshot in #21).
