### ISSUE TITLE
Japanese fonts are not displayed when navigating to control panel -> configuration -> server administration

### ISSUE THREAD

**Issue by timscottbell** [liferay/liferay-docker#21]
For our own Liferay image in DXP Cloud we noticed that Japanese does not display correctly on the server administration page. We fixed this by installing `fonts-takao-mincho` on top of the base `debian` image, and you'll likely have to do something similar for `alpine`.

**Comment by zsoltbalogh** [comment]
Haven't found the right package yet, unfortunately, still working on it. Just to double check, are you referring to these graphs?

![Screenshot 2019-10-08 at 10 06 48](https://user-images.githubusercontent.com/866157/66378313-7aca3200-e9b3-11e9-8482-319a0b98aabc.png)

**Comment by timscottbell** [comment]
@zsoltbalogh , yes

**Comment by zsoltbalogh** [comment]
Moved over to https://issues.liferay.com/browse/LPS-117911 to give better visibility of the issue. @timscottbell, please follow the ticket there. Sorry for the long delay on the resolution, this image is rarely used (as far as I understand this is only a cosmetical issue) and this is why it has a very low priority. If you find which packages needs to be installed on alpine to support this, that would be awesome, so far I was unsuccessful.
