### ISSUE TITLE
Broken Liferay image 

### ISSUE THREAD

**Issue by EugeneMsv** [liferay/liferay-docker#24]
After yesterday update during usage gradlew buildDockerImage we've got new portal image
![image](https://user-images.githubusercontent.com/11499112/66043003-a6b66500-e526-11e9-9312-416ee4695304.png)

And we discovered that portal-ext.properties didn't copy to /opt/liferay as a result container didn't work.

But image liferay/portal:7.2.0-ga1-201906281448 works fine

**Comment by amusarra** [comment]
I also found the same error.

```
[LIFERAY] To SSH into this container, run: "docker exec -it e1d77fa6cf7c /bin/bash".
/usr/local/bin/configure_liferay.sh: line 12: [: portal-ext.properties: binary operator expected
```

**Comment by zsoltbalogh** [comment]
Thank you @EugeneMsv - @amusarra fixed this issue in this PR: https://github.com/liferay/liferay-docker/pull/25

Once it's merged, we'll republish the images.

**Comment by zsoltbalogh** [comment]
We have republished the images 12 days ago after this change was merged, please reopen the issue if you still see this happening.
