### ISSUE TITLE
11311 is not exposed as by default it only listens on localhost

### ISSUE THREAD

**Issue by zsoltbalogh** [liferay/liferay-docker#28]

**Comment by gamerson** [comment]
Perhaps the issue is osgi.console is by default only binding to `localhost`, 

from `portal-developer.properties`
```
module.framework.properties.osgi.console=localhost:11311
```

I'm wondering if switching it to 
```
module.framework.properties.osgi.console=0.0.0.0:11311
```
would allow it to accept connections from docker host.

**Comment by gamerson** [comment]
so if you launch the container with these args, then it works.

```docker -e LIFERAY_MODULE_PERIOD_FRAMEWORK_PERIOD_PROPERTIES_PERIOD_OSGI_PERIOD_CONSOLE=0.0.0.0:11311 
 run -it liferay/portal:7.2.0-ga1-201911072159```

**Comment by zsoltbalogh** [comment]
Sent a PR to Brian with this property, thanks @gamerson for testing!
