### ISSUE TITLE
"Connection reset" when trying to debug liferay in the container

### ISSUE THREAD

**Issue by dsanz** [liferay/liferay-docker#35]
**Issue**
It's not possible to connect the debugger from the host to the container. If I run the container like this:
`docker run -it -e LIFERAY_JPDA_ENABLED=true -p 8080:8080 -p 8000:8000 {imageId}`
And then I try to start a debug session from the IntelliJ, I'm getting:
> Error running 'debug': Unable to open debugger port (localhost:8000): java.net.SocketException "Connection reset"

**Research**
According to this [stackoverflow question](https://stackoverflow.com/questions/47168235/cant-remotely-debug-on-java-9-tomcat-9-in-docker-container), the address parameter may require some change in Java 9. Given that we use Java 8 in our images, I tried the suggested solution but it did not work. At least, it gave me the clue.

**Workaround**
After some other attempts, I was able to attach a debugger by skipping the "localhost" portion of the address parameter, leaving just the port. That led me to this workaround:
`docker run -it -e LIFERAY_JPDA_ENABLED=true -e JPDA_ADDRESS=8000 -p 8080:8080 -p 8000:8000 {imageId}`

**Solution**
Ensure we override JPDA_ADDRESS if container is started with the debug env variable set

**Comment by zsoltbalogh** [comment]
This was fixed already.
