### ISSUE TITLE
Unable to connect via AJP with the container

### ISSUE THREAD

**Issue by dsanz** [liferay/liferay-docker#37]
**Observed behavior**
Dockerfile exposes ajp port. When you map port 8009 in the container, expectation is that pages can be served via ajp. However, tomcat will discard them. 

**Evidence**
Here are the apache2 error logs when configured as reverse proxy with ajp in the host machine, then http://localhost:80 is hit from a browser running in the host:
```
[Tue Dec 17 18:06:19.375949 2019] [proxy_ajp:error] [pid 4337:tid 140133135910656] (104)Connection reset by peer: AH01030: ajp_ilink_receive() can't receive header
[Tue Dec 17 18:06:19.375982 2019] [proxy_ajp:error] [pid 4337:tid 140133135910656] [client ::1:43648] AH00992: ajp_read_header: ajp_ilink_receive failed
[Tue Dec 17 18:06:19.375992 2019] [proxy_ajp:error] [pid 4337:tid 140133135910656] (120006)APR does not understand this error code: [client ::1:43648] AH00878: read response failed from [::1]:8009 (localhost)
[Tue Dec 17 18:06:19.454898 2019] [proxy_ajp:error] [pid 4337:tid 140133127517952] (104)Connection reset by peer: AH01030: ajp_ilink_receive() can't receive header
[Tue Dec 17 18:06:19.454933 2019] [proxy_ajp:error] [pid 4337:tid 140133127517952] [client ::1:43650] AH00992: ajp_read_header: ajp_ilink_receive failed, referer: http://localhost/
[Tue Dec 17 18:06:19.454943 2019] [proxy_ajp:error] [pid 4337:tid 140133127517952] (120006)APR does not understand this error code: [client ::1:43650] AH00878: read response failed from [::1]:8009 (localhost), referer: http://localhost/
```
**Analysis**
Reason is that current images are not enabling the ajp connector in tomcat. 
A workaround is to copy a new server.xml in /mnt/liferay/files/tomcat/conf/, where the ajp connector is uncommented, then start the container with a bind mount (-v):
```
<!-- Define an AJP 1.3 Connector on port 8009 -->
<Connector port="8009" protocol="AJP/1.3" redirectPort="8443" URIEncoding="UTF-8" />
```
Default config comes with that one commented out.

**Solution**
Image builder should provide a properly configured tomcat

**Comment by zsoltbalogh** [comment]
@dsanz, for me the tomcat we package into the images listen on *:8009. Could you please double check what was causing the problem for you?

**Comment by dsanz** [comment]
Hi @zsoltbalogh ,

I've double checked everything, this time I've also used the new image. Tomcat we ship liferay/dxp:7.2.10.1 is not listening 8009. liferay/dxp:7.2.10.1-sp1 neither. We just expose the port in the Dockerfile but nothing listens in the container.

To avoid any potential apache2 conf on my side, I've also checked the opened ports in the container.

Just run it and map the port
```
$ docker run -p8009:8009 -it liferay/dxp:7.2.10.1
[LIFERAY] To SSH into this container, run: "docker exec -it 896178b8849a /bin/bash".
```
Wait till tomcat starts. Then connect to the container and ask for opened ports:
```
liferay@896178b8849a /opt/liferay 
$ netstat -lntup
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:8005          0.0.0.0:*               LISTEN      8/java
tcp        0      0 0.0.0.0:11311           0.0.0.0:*               LISTEN      8/java
tcp        0      0 127.0.0.1:9200          0.0.0.0:*               LISTEN      8/java
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      8/java
tcp        0      0 127.0.0.1:9300          0.0.0.0:*               LISTEN      8/java
```
There is no 8009. Using this configuration for apache2 mod_proxy (with ajp plugin enabled) in the host:
`ProxyPass "/" "ajp://localhost:8009/"
`
Accesing http://localhost gives a "Service Unavailable page"
This is consistent with the fact that tomcat connector is commented out:
```
liferay@896178b8849a /opt/liferay
$ cat /opt/liferay/tomcat-9.0.17/conf/server.xml | grep 8009
    <!-- Define an AJP 1.3 Connector on port 8009 -->
    <!-- <Connector port="8009" protocol="AJP/1.3" redirectPort="8443" URIEncoding="UTF-8" /> -->
```
Now, let's use a different tomcat/conf/server.xml via bind mount, where I uncommented the ajp connector:
```
$ docker run -p8009:8009 -it -v /home/dsanz/projects/liferay-docker-tests/mnt-config-tests/:/mnt/liferay liferay/dxp:7.2.10.1
[LIFERAY] To SSH into this container, run: "docker exec -it c990bb329fdc /bin/bash".

[LIFERAY] Copying files from /mnt/liferay/files:

/mnt/liferay/files
├── portal-ext.properties
└── tomcat
    ├── conf
    │   ├── server.xml

...
```
Double check that tomcat connector is uncommented in the container:
```
$ cat /opt/liferay/tomcat-9.0.17/conf/server.xml | grep 8009
    <!-- Define an AJP 1.3 Connector on port 8009 -->
    <Connector port="8009" protocol="AJP/1.3" redirectPort="8443" URIEncoding="UTF-8" />
```
Let's see the opened ports now:
```
liferay@c990bb329fdc /opt/liferay 
$ netstat -lntup
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:8005          0.0.0.0:*               LISTEN      11/java
tcp        0      0 0.0.0.0:8009            0.0.0.0:*               LISTEN      11/java
tcp        0      0 0.0.0.0:11311           0.0.0.0:*               LISTEN      11/java
tcp        0      0 127.0.0.1:9200          0.0.0.0:*               LISTEN      11/java
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      11/java
tcp        0      0 127.0.0.1:9300          0.0.0.0:*               LISTEN      11/java

```
Now we have a socket listening at 0.0.0.0:8009. With same apache2 conf, accessing http://localhost takes me to the license_lcs page

Our official bundles are not configuring tomcat to enable ajp either, so uncompressing a bundle directly in the host has the same results, I reproduced this same steps in the non-containerized installation.

Just in case I've missed anything: how did you made it work? Perhaps a different webserver/config? Do you get tomcat listingin to 8009 port just by running the ootb container?

Thank you

**Comment by zsoltbalogh** [comment]
This is getting interesting :) Let me look into this, all of the server.xml's I have seen yesterday had 8009 enabled.

**Comment by dsanz** [comment]
I'm closing this because we agreed that AJP connector shall be enabled/disabled by the container's entry point via env variable. This way, it will come disabled by default (AJP port will remain exposed), and can be enabled when running the container, very much like debuggin works

**Comment by chandu2035** [comment]
This is what I used to get it worked in server.xml
 
<Connector protocol="AJP/1.3"
               address="::"
               secretRequired="false"
               port="8009"
               redirectPort="8443" />
