### ISSUE TITLE
Unable to build image

### ISSUE THREAD

**Issue by vaibhatr** [liferay/liferay-docker#38]
I am facing following issue while creating image. Logs shown below:- 

C:\Code\docker\liferay-docker-master>docker build template -t liferay-portal
Sending build context to Docker daemon  13.82kB
Step 1/32 : FROM azul/zulu-openjdk-alpine:8u232
 ---> 97bb12e9b796
Step 2/32 : ARG LABEL_BUILD_DATE
 ---> Using cache
 ---> 937be184448d
Step 3/32 : ARG LABEL_NAME
 ---> Using cache
 ---> ef025e9c9c65
Step 4/32 : ARG LABEL_VCS_REF
 ---> Using cache
 ---> c0180ac9ff2a
Step 5/32 : ARG LABEL_VCS_URL
 ---> Using cache
 ---> 7909d196ecc1
Step 6/32 : ARG LABEL_VERSION
 ---> Using cache
 ---> cd5a454fbc37
Step 7/32 : RUN apk add bash curl nss tomcat-native tree ttf-dejavu
 ---> Using cache
 ---> f7f99bf256a5
Step 8/32 : COPY scripts/* /usr/local/bin/
 ---> Using cache
 ---> 8ebf7684f09f
Step 9/32 : RUN adduser -D -h /home/liferay liferay && addgroup liferay liferay
 ---> Using cache
 ---> 3fe4150cdfc8
Step 10/32 : COPY --chown=liferay:liferay home/.bashrc /home/liferay/
 ---> Using cache
 ---> 30b5cecd3287
Step 11/32 : COPY --chown=liferay:liferay liferay /opt/liferay
COPY failed: stat /var/lib/docker/tmp/docker-builder924338140/liferay: no such file or directory

Can anyone please help me resolve this issue. Thanks in advance.

**Comment by zsoltbalogh** [comment]
Hi @vaibhatr - I'm sorry it took so long to respond, there was a problem with the e-mail notifications and this is not the system we use to track issues so we don't come here day-to-day. 

Using the template is not enough to build the image as we are using the scripts to prepare the folder before we call `docker build`. If you'd like to use this tool, I'd recommend the `build_local_image.sh` which can help you to properly set up the folder before starting the docker build process.

If you don't need to build Liferay Portal / DXP from source and you'd just like to package your addons, I recommend to use Liferay Workspace: https://portal.liferay.dev/docs/7-1/tutorials/-/knowledge_base/t/leveraging-docker
