### ISSUE TITLE
Non-DXP images still try to patch liferay

### ISSUE THREAD

**Issue by dsanz** [liferay/liferay-docker#39]
Container entrypoint attempts to patch liferay if the mounted volume includes a `patching/` directory. This logic shall be run only if the image is a DXP one. For portal (CE) images, the existence of such directory must be ignored.

**Observed behavior**
Container tries to run the patching tool, which causes some errors as it does not come with the CE image:

> /usr/local/bin/patch_liferay.sh: line 47: /opt/liferay/patching-tool/patching-tool.sh: No such file or directory
> cp: can't create '/opt/liferay/patching-tool/patches': No such file or directory
> /usr/local/bin/patch_liferay.sh: line 6: /opt/liferay/patching-tool/patching-tool.sh: No such file or directory
> /usr/local/bin/patch_liferay.sh: line 8: /opt/liferay/patching-tool/patching-tool.sh: No such file or directory

If a patching tool is provided in the bind mount directory, container tries to install it, then patch liferay:

> [LIFERAY] Updating Patching Tool.
> mv: can't rename '/opt/liferay/patching-tool/patches': No such file or directory
> Directory is not set in command line, using ../
> Auto discovery looks for portal segments. The selected directory is "/opt/liferay".
> Configuration has been written into the default.properties:
> 
> patching.mode=binary
> war.path=../tomcat/webapps/ROOT/
> global.lib.path=../tomcat/lib/ext/
> liferay.home=../
> 
> mv: can't rename '/opt/liferay/patching-tool-upgrade-patches': No such file or directory
> 
> [LIFERAY] Patching Tool updated successfully.
> Problem with the configuration: Couldn't find the patches folder: patches/
> Problem with the configuration: Couldn't find the patches folder: patches/
> Problem with the configuration: Couldn't find the patches folder: patches/

**Solution**
Check that image is a DXP one before attempting to patch

**Comment by andrebiegel** [comment]
btw when trying to patch .. liferay/dxp:7.2.10.1-sp1-202001171544

> This installation does not include data for patching. Please download the '7.2.10.1-sp1-20191009103614075' Patching Data file from the Customer Portal to the "patches" folder and run patching-tool setup.

**Comment by zsoltbalogh** [comment]
@andrebiegel this is intentional. We are planning to release a new docker image for each fix pack so we won't need to install fix packs at startup time. The patch installation is mostly for hotfixes and for that you should not receive this message (please let us know is a separate issue if it is). If you need to install a fix pack, you'd need to put the patching data file and the fix pack into the mounted patches folder.

Closing this ticket as the change had been merged.

**Comment by andrebiegel** [comment]
@zsoltbalogh  .. Thx for the insight ..

**Comment by zsoltbalogh** [comment]
@andrebiegel we are working on improving the documentation - this should be quite straightforward in the future. We just need to get the fix pack images how which we might be able to do shortly.
