### ISSUE TITLE
Updating patching tool in the container requires renaming the patching tool .zip file

### ISSUE THREAD

**Issue by dsanz** [liferay/liferay-docker#40]
Liferay subscribers can download the patching tool from the customer portal. Older versions were named `patching-tool-x.y.zz.zip`, more recent ones (released during 2019) are named `Patching Tool x.y.zz.zip`

Container looks for a patching tool file in the bind mounted volume. If tool is found, then it is installed prior to patch Liferay,

**Observed behavior**
Only old naming files are recognized as valid patching tool. New names are ignored, so users need to know how to rename the .zip file to match old naming convention if they have to update the patching tool in the container

**Solution**
Either consider only new names or both

**Comment by zsoltbalogh** [comment]
Thank you for catching this! It's a naming issue with Patching Tool so I've asked the team who is responsible for the Customer Portal to use the right file names: https://issues.liferay.com/browse/LRSUPPORT-36097

As this feature would be required a very little number of times and the risk of someone running into this from our customers would be very risky, I won't include this change. 

Thank you for catching this issue!
