### ISSUE TITLE
Liferay deployment on openshift codeready 4.3 

### ISSUE THREAD

**Issue by doyoungim999** [liferay/liferay-docker#48]
Hi I deployed liferay docker to openshift and received an error : 
$oc new-app --docker-image=liferay/portal:7.1.0-ga1-201809012030

[LIFERAY] To SSH into this container, run: "docker exec -it portal-1-dhkpr /bin/bash".

[LIFERAY] Run this container with the option "-v ${pwd}/xyz123:/etc/liferay/mount" to bridge ${pwd}/xyz123 in the host operating system to /etc/liferay/mount on the container.

[LIFERAY] The directory /etc/liferay/mount/files does not exist. Files in /etc/liferay/mount/files will be automatically copied to /opt/liferay before Liferay Portal starts.

[LIFERAY] The directory /etc/liferay/mount/scripts does not exist. Files in /etc/liferay/mount/scripts will be automatically executed, in alphabetical order, before Liferay Portal starts.

[LIFERAY] Starting Liferay Portal. To stop the container with CTRL-C, run this container with the option "-it".

/etc/liferay/entrypoint.sh: line 52: /opt/liferay/tomcat/bin/catalina.sh: Permission denied

What is the solution to fix?

**Comment by doyoungim999** [comment]
I resolved

**Comment by zsoltbalogh** [comment]
Thanks for updating the ticket, closing!

**Comment by MarcoPortillo** [comment]
@doyoungim999 I have the same problem, how did you resolve it?

**Comment by doyoungim999** [comment]
@MarcoPortillo 

you may try this: 

$oc create serviceaccount useroot
$oc  adm policy add-scc-to-user anyuid -z useroot
$oc edit dc/portal 
   spec:
   serviceAccountName: useroot

**Comment by MarcoPortillo** [comment]
@doyoungim999 It does not work, it says my user does not have permission to do this

**Comment by doyoungim999** [comment]
I don't know the error message. 
You need openshift admin user authority to create service account.

**Comment by MarcoPortillo** [comment]
@doyoungim999 Can I contact you somehow to explain better? I am new to Liferay, docker and openshift so I am kinda lost with the steps. If you have time

**Comment by doyoungim999** [comment]
Are you running on openshift ? 
I am not liferay expert either.
Please describe the steps in detail with your error here.

**Comment by MarcoPortillo** [comment]
@doyoungim999 Yes, openshift 4.5 and Liferay 7.2.

First I created my docker image from my Liferay Environment, I use these steps: https://help.liferay.com/hc/en-us/articles/360022307392-Leveraging-Docker

Second, I found about this Openshift-ready liferay image project: https://hub.docker.com/r/simontim/liferay-openshift if I use this image directly in my openshift environment, I don't have any permission issues, even using the same user and it works perfectly but is liferay 7.0 and I need 7.2 with all my projects and configs. I tried to copy the steps he uses in his DOCKERFILE in my local dockerfile (of course, adapting my paths), but still doesn't work.

Lastly, I just upload my docker image to docker hub and pull from there to my openshift environment. I get these errors:

![image](https://user-images.githubusercontent.com/21960445/98138584-8c864d80-1ec3-11eb-8c75-473696d84f2b.png)

this happen when I start the pod and it tries to start the liferay instance.

I also tried your steps, but I get this message error:

![image2](https://user-images.githubusercontent.com/21960445/98138957-edae2100-1ec3-11eb-8314-d7cb24f7e360.png)

I would really thankful if you could help me somehow 👍

**Comment by doyoungim999** [comment]
permission denied can be related with serviceaccount in openshift. 
If you're using podman or docker, you will not have this error. 
So i suggest you create service account with administroator "kubeadmin". 
after you create a serviceaccount, you need to add serviceAccountname in deployment disciptor  like th attached. 
I run the following in my case: 
$oc edit deployment portal 
![image](https://user-images.githubusercontent.com/6082088/98205453-29ec8a80-1f73-11eb-96f0-c7895a33c3ca.png)

**Comment by MarcoPortillo** [comment]
@doyoungim999 thank you, unfortunately we don't have access to create a service account with administrator "kubeadmin"

I have a jenkins instance in my openshift, do you think if I try to create my liferay docker image directly there, it could make a difference?
