### ISSUE TITLE
What is username and password to run docker : 7.3.0-ga1 ?

### ISSUE THREAD

**Issue by doyoungim999** [liferay/liferay-docker#49]
Hi 
I run 2 images and 2 of the does not have "basic configuration" 
docker pull liferay/portal:7.3.0-ga1-202003272258
docker pull liferay/portal:7.3.0-ga1

What is  username and password?

**Comment by zsoltbalogh** [comment]
Hi @doyoungim999 , 

It's test@liferay.com and test. We are working on updating the documentation and add these details.

Zsolt
