### ISSUE TITLE
liferay/portal:7.3.1-ga2 in openshift 4.3.1

### ISSUE THREAD

**Issue by doyoungim999** [liferay/liferay-docker#50]
Hi 
I have an issue with 7.3.1 docker version in openshift 4.3.1
$oc new-app  --docker-image=liferay/portal:7.3.1-ga2-202004031138
$oc logs portal2-2-lxn6k
**The connection to the server api.crc.testing:6443 was refused - did you specify the right host or port?**
I did not have any problem with 7.1.0 before 
$oc new-app --docker-image=liferay/portal:7.1.0-ga1-201809012030

Is there any difference ?

**Comment by doyoungim999** [comment]
What is id/password?

**Comment by zsoltbalogh** [comment]
@doyoungim999 , do you still face the same issue? Can you please try to point out what's the issue with the docker image without openshift? I'd be able to help you better. If so, please open an LPS ticket on https://issues.liferay.com with the Docker Images component, that speeds up issue resolution.

The Liferay Portal or DXP default id/password is test@liferay.com / test.

Thank you,
Zsolt

**Comment by doyoungim999** [comment]
I resolved this issue. Thank you.

**Comment by zsoltbalogh** [comment]
Awesome, thank you for the fast response!
