### ISSUE TITLE
Error in cleanup when everything went correctly

### ISSUE THREAD

**Issue by ethanbustad** [liferay/liferay-docker#51]
Building a new image on 7.3.10 EA2 using the `build_local_image.sh` script gave me the following output:

```
...
Successfully tagged 7.3.10-ea2:20200327164108906
Starting container from image 7.3.10-ea2:20200327164108906-202004281138.
Waiting for health status.....................
[test_health_status] SUCCESS
[test_docker_image_files] SUCCESS
[test_docker_image_fix_pack_installed] SUCCESS
[test_docker_image_scripts_1] SUCCESS
[test_docker_image_scripts_2] SUCCESS
Stopping container.
./test_image.sh: line 25: [: -eq: unary operator expected
```

It seems that bash (at least on my machine, Ubuntu 18.04) expects `TEST_RESULT` to be defined, and since it isn't defined in this case, then it errors out.

I think this should be solvable by either using quotes around both the variable and the test value (i.e. `"0"`), or initializing the variable as `=0` so that the equality test is evaluated properly.

**Comment by zsoltbalogh** [comment]
Moving to the LPS project to track: https://issues.liferay.com/browse/LPS-112892

**Comment by zsoltbalogh** [comment]
Sent PR for Brian to solve the issue.
