### ISSUE TITLE
Question about "docker pull liferay/portal:7.3.1-ga2"

### ISSUE THREAD

**Issue by doyoungim999** [liferay/liferay-docker#52]
Hi 
Is there any steps or environment variable to to run startup.sh as the first time docker ? 
https://learn.liferay.com/dxp-7.x/installation-and-upgrades/installing-liferay/running-liferay-for-the-first-time.html#start-liferay-dxp

**Comment by zsoltbalogh** [comment]
@doyoungim999 , I'm not sure if I understand your question. Liferay Portal automatically starts up when you start the container, there's nothing extra you need to do. 

The documentation is available here: https://learn.liferay.com/dxp/7.x/en/installation-and-upgrades/installing-liferay/using-liferay-dxp-docker-images/dxp-docker-container-basics.html
