### ISSUE TITLE
Not able to use xuggler on liferay's docker image

### ISSUE THREAD

**Issue by asotog** [liferay/liferay-docker#54]
Using Gradle wrapper docker scripts, getting core dumps errors when the server is trying to generate a video preview

Liferay 7.2

liferay.workspace.docker.image.liferay=liferay/dxp:7.2.10-dxp-4-202003280246

it is DXP but I suppose happens same with regular portal version

**Comment by zsoltbalogh** [comment]
Thank you, @asotog, for reporting this issue! I have created an LPS ticket to track the progress of this issue. Please follow it over there and provide any additional details you might have. Thank you!
