### ISSUE TITLE
JDK confusion

### ISSUE THREAD

**Issue by mimimircea** [liferay/liferay-docker#55]
Hello,
Why use a zulu-openjdk-alpine:8u232 image and download a zulu11-jdk only to set java version back to 8?
Wouldn't be easier just use a zulu 11 docker image, and use jdk 11?
It would shrink the Liferay image also. 

Edit: maybe provide 2 tags, one for JDK 11 and one for JDK 8..

**Comment by zsoltbalogh** [comment]
Thank you, @mimimircea for the feedback! Your recommendation was on the table when we chose to add both JDKs to the image. The goal was to limit the number of combinations we would need to prepare. Some of our users / customers still need to run on JDK8 and this is why we add the JDK8 support (and choose it as a default). In the long run we might be able to publish multiple images with different JDKs, currently it's not on the roadmap.
