### ISSUE TITLE
web.server.display.node=false is not affecting the platform

### ISSUE THREAD

**Issue by KOSSOKO** [liferay/liferay-docker#59]
We use Liferay docker image with kubernetes.

Liferay version 7.3.2 : http://liferay-test.esa-maap.org/web/guest

We noticed that Liferay added a label to show node by default, and in our example we have something like: Node: liferay-5d8d6d44bc-7tlx6:8080

According to [this](https://liferay.dev/blogs/-/blogs/where-am-i-how-to-know-which-cluster-node-you-re-on-) documentation, just adding web.server.display.node=false should remove the alert with node name.

But it is not working. The property is correctly set in the running container but this alert is still there. Please, how could I remove it ?

Thanks

**Comment by zsoltbalogh** [comment]
Hi @KOSSOKO, 

I've tried to reproduce the problem with the image you have shared, however I couldn't reproduce and couldn't find any evidence why it would happen. The web.server.display.node variable could be set using the LIFERAY_WEB_PERIOD_SERVER_PERIOD_DISPLAY_PERIOD_NODE, could you please check if it's not set in any of your scripts?

Here are the portal related environment variables (and configuration) which we set for Docker:
https://github.com/liferay/liferay-docker/blob/master/templates/bundle/Dockerfile#L23

**Comment by KOSSOKO** [comment]
Hello @zsoltbalogh, I tried on my local machine (Windows 7) the property work `web.server.display.node ` works fine. Still not working on kubernetes. I tried many solutions without success.

I hide the alert displaying node name using css in Theme, but it has impact on all alert type info

**Comment by zsoltbalogh** [comment]
Thank you for the quick answer! I have checked the source code and as far as I can see, this is only controlled by the property you have mentioned above. Are you using this image: liferay/portal:7.3.2-ga3? Do you have any extra layers on it?

**Comment by KOSSOKO** [comment]
yes I user the image liferay/portal:7.3.2-ga3 without any layer. 
I use this blog tutorial to deploy my liferay on Kubernetes.
https://liferay.dev/blogs/-/blogs/deploying-liferay-7-3-in-kubernetes

I did nothing special.

**Comment by zsoltbalogh** [comment]
Hi @KOSSOKO,

Thank you for sharing the link!

I've found the root cause, it's in the kubernetes configuration:
https://github.com/marcialcv/liferayk8s/blob/master/liferay-deployment.yaml#L71

Please change that configuration to remove the message if you still need to make it happen. Thank you for your fast responses on this ticket!

Zsolt
