### ISSUE TITLE
Can't find Liferay Filesystem on Host

### ISSUE THREAD

**Issue by netlander** [liferay/liferay-docker#60]
Since large files uploaded to the Documents and Media Portlet are not stored in the Database, where are they stored?

Starting the server with this option `-v $(pwd)/xyz123:/mnt/liferay` doesn't seem to give access to Liferay's file system for the purposes of backing up the data in case of restart.

What is the recommended approach for backing up Liferay data to survive a Docker container restart?

**Comment by balcsida** [comment]
Hi @netlander,

Liferay has multiple file system storage options, from which, by default, it uses the Simple File System Store (it is possible to [store files as BLOBs in database with DBStore](https://learn.liferay.com/dxp/7.x/en/system-administration/file-storage/other-file-store-types/dbstore.html)).

The official docker images uses the following path to store the uploaded files
```
/opt/liferay/data/document_library/
```

Our recommendation is to store the whole `data` directory in a volume, as other necessary information might be stored there that should be good to be kept between container recreation/deletion.

Docker run command example (excerpt):
```
-v $(pwd)/liferay-data:/opt/liferay/data
```

docker-compose.yml example (excerpt):
```yaml
    volumes:
      - type: volume
        source: liferay-data
        target: /opt/liferay/data
```

The mentioned `/mnt/liferay` path is useful when you would like to apply to some override to the files on `/opt/liferay` path (which is the Liferay Home directory).


I hope this answers your question.

For more information, please check the following documentation articles:
- [Configuring File Storage](https://learn.liferay.com/dxp/7.x/en/system-administration/file-storage/configuring-file-storage.html)
- [Simple File System Store](https://learn.liferay.com/dxp/7.x/en/system-administration/file-storage/other-file-store-types/simple-file-system-store.html)
- [Other File Store Types](https://learn.liferay.com/dxp/7.x/en/system-administration/file-storage/other_file_store_types.html)

Kind regards,
@balcsida

**Comment by zsoltbalogh** [comment]
Hi @netlander , I'm closing the ticket per @balcsida 's comment. Please reopen if his comment didn't solve the problem you were facing. Thank you!
